# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: collabfield_development
  username: collabfield
  password: 123456
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: collabfield_test
  username: collabfield
  password: 123456

production:
  <<: *default
  database: collabfield_production
  username: collabfield
  password: <%= ENV['COLLABFIELD_DATABASE_PASSWORD'] %>
